In [1]:
import numpy as np 

In [3]:
mx_1s  = np.array([[1,1,1],[1,1,1],[1,1,1]]) #created a matrix
print(mx_1s) 

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
mx_1s = np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [9]:
mx_1s = np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
mx_1s = np.ones((3,4), dtype= int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [13]:
mx_0s = np.zeros((2,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [15]:
mx_0s = np.zeros((3,6), dtype = bool) #convert the data type
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [17]:
mx_em = np.empty((3,3))
print(mx_em)

[[0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 9.25e-321]
 [0.00e+000 0.00e+000 0.00e+000]]
