Numpy function:

In [5]:
import numpy as np 

arange()


In [7]:
#np.arange(start, End , steps)
ar_1d = np.arange(1,13)
print(ar_1d)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


linspace()

In [8]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

reshape()

conver 1D array to 2D array or 3D array

In [9]:
ar_2d = ar_1d.reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [10]:
ar_3d = ar_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [13]:
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


ravel()

conver multi D array to 2 D array

In [14]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

flatten()

transpose()

In [15]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])