In [3]:
import numpy as np 

In [5]:
arr_1d =np.array([1,2,3,4]) #creat an 1d array
print(arr_1d)

[1 2 3 4]


In [6]:
type(arr_1d) #find the type of array

numpy.ndarray

In [21]:
arr_1d.ndim

1

In [13]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])  #creat an 2D array
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
arr_2d.ndim # find the dimention

2

In [18]:
arr_1d.size  #find out how many element are in the array

4

In [17]:
arr_2d.size

8

In [19]:
arr_2d.shape #find the shape in the array how many row and coloum are presnt in the array
#(row , colm)

(2, 4)

In [20]:
arr_2d.dtype #find the data type in an array 

dtype('int32')