Mathematic Operation Using NumPy

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [10]:
np.add(arr1, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [13]:
np.subtract(arr1 , arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
arr1 / arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.divide(arr1 , arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [18]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [19]:
arr1.max() # to find the maximum value

9

In [20]:
arr1.argmax() # find the index value of the maximum value

8

In [22]:
arr1.max(axis = 0)  # find the maximum value in a coloum

array([7, 8, 9])

In [23]:
arr1.max(axis = 1) # find the maximum value in row

array([3, 6, 9])

In [25]:
arr1.min() # to find the min value

1

In [26]:
 arr1.argmin() # find the min value index

0

In [27]:
arr1.min(axis = 0) # find the min value in the coloum 

array([1, 2, 3])

In [29]:
np.sum(arr1) # add each element of thr array

45

In [30]:
np.sum(arr1, axis= 0)# to add each coloum of the matrix

array([12, 15, 18])

In [32]:
np.mean(arr1) # find the avg of the array

5.0

In [33]:
np.sqrt(arr1)#find the sqare root of the array

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [34]:
np.log(arr1)# find the log of the array

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [36]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])