Random Sampling with Numpy

In [2]:
import numpy as np
import random 

In [5]:
np.random.random(1) # It will the random function

array([0.74831087])

In [12]:
np.random.random((3,3)) # it will give random 2D  Array, But it will give the random float

array([[0.55974206, 0.91401561, 0.38728305],
       [0.38054589, 0.13915178, 0.18860402],
       [0.29789671, 0.79724425, 0.54189078]])

In [10]:
np.random.randint(1,4) # it will the give one random number

2

In [14]:
np.random.randint(1,4, (4,4)) # it will give the random int value in 4 by 4 matrix 2D Array

array([[3, 3, 1, 2],
       [2, 1, 3, 1],
       [2, 1, 1, 2],
       [1, 3, 1, 3]])

In [15]:
np.random.randint(1,4, (2,4,4)) #It will give random int value in 4 by 4 marix in #D array 

array([[[2, 1, 1, 3],
        [2, 2, 3, 1],
        [2, 2, 1, 3],
        [2, 1, 3, 2]],

       [[2, 2, 3, 3],
        [2, 1, 3, 3],
        [1, 3, 2, 3],
        [2, 1, 3, 1]]])

In [16]:
np.random.seed(10) # the number will be same every time we use seed function
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [18]:
np.random.rand(3) # it will give only random float value

array([0.58390137, 0.18263144, 0.82608225])

In [20]:
np.random.randn(3,3) # It will give -ve and +ve value

array([[ 1.13912535,  0.36221796, -0.59091299],
       [ 0.38936304, -0.52699615, -0.51430791],
       [ 0.89760917,  0.98925209,  0.25922513]])

In [23]:
x = [1,2,3,4]
np.random.choice(x)    # it will give one random choise from the list "x"

2

In [25]:
for i in range(20):  # it will give continious 20 random value from list "x"
    print(np.random.choice(x))

3
2
2
4
2
3
2
1
2
2
2
1
3
4
4
2
1
1
3
1


In [26]:
x

[1, 2, 3, 4]

In [27]:
np.random.permutation(x)

array([4, 1, 2, 3])

 https://docs.python.org/3/library/random.html # this the link to the some more random funtion 